image: debian

stages:
- update
- analyze
- test
- build

update:
    stage: update
    script:
        - apt update
        - apt upgrade -y
        - apt install -y g++ make libgtest-dev astyle
        
analyze:
    stage: analyze
    script: make analyze

test:
    stage: test
    script: make test

build:
    stage: build
    script: make