image: ubuntu

stages:
- update
- make

update:
    stage: update
    script:
        - apt update
        - apt upgrade -y
        - apt install g++ make libgtest-dev astyle
        
make:
    stage: make
    script: make